### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by kdhaka94** [AmmeySaini/Realme-AutoBuy#1]
How to set the cookies, its prompting install chrome and i cant seem to find whats causing the issue

**Comment by Roshankumar2** [comment]
basically you have to save your cookies in my cookies folder where in the sequence in sessionId||opkey||newopkey and save into txt format
after that run the code "python run.py"

**Comment by 0xjas0** [comment]
@kdhaka94 If you are using latest version of chrome browser i want to let you know that chrome has fixed some vulnerabilities with their newer version so you might not be able to create cookie file with script 
**FIXES**
Either use older version of chrome browser or use firefox browser for logging in your account and then generating cookie file with script or use manual method (Check readme for this)

**Comment by Roshankumar2** [comment]
You can get manually cookies..by inspecting sites

**Comment by Roshankumar2** [comment]
Hey bru could you allow me to know more about your script.. which is totally based on python
As like about qty select option
Or at a time it carry 2 or more cookies at a same time and in a one enter button it will add product into cart with different cookies and as the result we will get three order no  for next steps..

**Comment by kdhaka94** [comment]
@AmmeySaini Gotcha! Thnx , N can u tell me how u come to know about this api.realme.com because I googled it but nothing popped up
