### ISSUE TITLE
it showing me "Sorry, {0} has sold out" wherever stock is still live. 

### ISSUE THREAD

**Issue by Roshankumar2** [AmmeySaini/Realme-AutoBuy#2]
bro loved your work awesome order technique :)
it showing me "Sorry, {0} has sold out" wherever stock is still live. plz resolve this also
![git](https://user-images.githubusercontent.com/67075491/88174565-1b879680-cc42-11ea-9e36-70191345dcc0.png)

**Comment by ram965** [comment]
Bro can you provide me a video plz , any user or github team ?

**Comment by ram965** [comment]
@roshankumar2 bro plz can u contact me via whatsapp 9499411406, i want to ask you something about the working of this script

**Comment by 0xjas0** [comment]
@Roshankumar2 i have recently checked adding a stocked product to cart and it worked well for me. The issue you might be facing is due to ending of stock during the sale or you started script late (IN SIMPLE WORDS YOU MISSED THE SALE)

**Comment by Roshankumar2** [comment]
> @Roshankumar2 i have recently checked adding a stocked product to cart and it worked well for me. The issue you might be facing is due to ending of stock during the sale or you started script late (IN SIMPLE WORDS YOU MISSED THE SALE)

Bruh could you plz also add auto loading till sale is not on..if sale will on it automatically add into cart and so on...
