### ISSUE TITLE
Sale time Issue 

### ISSUE THREAD

**Issue by yogeshapoorva511** [AmmeySaini/Realme-AutoBuy#8]
Sale time issue At the time of sale, it comes to the issue that this script has to select which color and which variant to take and how much quantity is required.  I do not understand the script.At the time of the sale, I try, the order ID arrives but the cart remains empty.

**Comment by 0xjas0** [comment]
script automatically selects available colors and if you order more than 1 quantity the chances gets higher for cancellation

**Comment by yogeshapoorva511** [comment]
Can you make me a video, and do you have a script for mi store and amazon too sir

**Comment by naveen0788** [comment]
Sir in my pc script is not working
Even though i have installed all softwares
